### ISSUE TITLE
Great Project!

### ISSUE THREAD

**Issue by idkjs** [Saityi/a-tour-of-standard-ml#3]
Thanks for sharing it.

Also learned something about haskell site generation.

This would be infinitely more useful if you showed how to call the functions. Is that in your plans?

For example below, if we add:
```
val x = (inc' 1) = (inc 1) (* true *)
```
to https://github.com/Saityi/a-tour-of-standard-ml/blob/f84ce850015da48df0e3e8849702686461751fff/examples/01-04-functions.sml#L12

 `val _` doesn't show up in the output but x does.

```
[opening 01-04-functions.sml]
val inc = fn : int -> int
val add = fn : int -> int -> int
val inc' = fn : int -> int
val x = true : bool
```

Another thought to put this over the top would be to change your filenames so that typing them into the repl is not completely tedious which it is now!

You are the best, friend. Peace to you. Thank you for sharing this work.

**Comment by Saityi** [comment]
Hi, thank you! Yes, I think changing the throwaway name `_` to an actual name (like `x`) would be a good idea here; it will show up in the signature and improve discoverability at the REPL. It wasn't in my plans, but I will look into it 😃

And a good point about the tedium, too -- what would you find preferable? Maybe just the chapter numbers as file names e.g., `00-00.sml`? Would that be too nondescript? I was hoping by naming the files they would be easy to discover, but maybe since the primary usage is intended to be via the webtour, that isn't really relevant. What do you think?

**Comment by idkjs** [comment]
Definitely, not numbers. I went through many of the examples. Very tedious indeed. I say names. That is how you will identify with the file anyway, if its an on point, descriptive name like many of them are AFTER the numbers.
